# See ./.docker/README.md for details about this file
version: '2'

volumes:
  data_volume:
    driver: local

services:
  web:
    image: 1and1internet/ubuntu-16-apache-php-7.2
    environment:
      DOCUMENT_ROOT: web
    ports:
      - "8000:8080" # load the site via http://localhost:8000
    volumes:
      - .:/var/www
      - ./.docker/web/php-craft.ini:/etc/php/7.2/apache2/conf.d/99-craft.ini
      - ./.docker/web/vhosts-std-logging.conf:/etc/apache2/conf-enabled/vhosts-std-logging.conf
      - ./.docker/web/hooks/sendmail_setup:/hooks/supervisord-pre.d/99_sendmail_setup
    depends_on:
      - mysql
#      - redis
    links:
      - mysql
#      - redis

  mysql:
    image: mysql:5.7
    ports:
      - "13306:${DB_PORT}" # Exposes mysql on localhost at DB_PORT (in .env file)
    expose:
      - 3306
    volumes:
      - data_volume:/var/lib/mysql
      - ./.docker/mysql/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

# Uncomment this if you want to use redis locally. Also, uncomment the
# `depends_on` and `links` sections above for the web container. You will
# also need to update your .env file to set the REDIS_URL
#  redis:
#    image: redis:3.2
